#!/usr/bin/env python3
import sys
import sqlite3
import uuid
from urllib.parse import (
    unquote,
    urlparse,
    urlunparse,
    urlencode,
    parse_qsl,
    ParseResult,
)

TOKEN_NAME = "HAVEWEMETUUID"

# Wrapper class to hide DB implementation
class DbConnector(object):
    def __init__(self):
        self.con = sqlite3.connect("havewemet.db")
        self.con.execute(
            "create table if not exists netlocs(netloc varchar(255) unique)"
        )
        self.con.execute("create table if not exists tokens(token varchar(255))")

    def getNetloc(self, netloc):
        with self.con:
            res = self.con.execute("select * from netlocs where netloc = ? ", [netloc])
            if res.fetchone() is None:
                return False
            else:
                return True

    def addNetloc(self, netloc):
        with self.con:
            self.con.execute("insert into netlocs(netloc) values (?)", [netloc])

    def addToken(self, token):
        with self.con:
            self.con.execute("insert into tokens(token) values (?)", [token])

    def getToken(self, token):
        with self.con:
            res = self.con.execute("select * from tokens where token = ? ", [token])
            if res.fetchone() is None:
                return False
            else:
                self.con.execute("delete from tokens where token = ? ", [token])
                return True


db = DbConnector()

while True:
    info = sys.stdin.readline()
    url = unquote(info.split(" ")[0].strip())
    url_parsed = urlparse(url)
    query = dict(parse_qsl(url_parsed.query))
    netloc = url_parsed.netloc
    if TOKEN_NAME in query:
        if db.getToken(query[TOKEN_NAME]):
            db.addNetloc(netloc)
            print("OK", flush=True)
        else:
            # TODO Alert?
            pass
    elif db.getNetloc(netloc):
        print("OK", flush=True)
    else:
        hwm_uuid = str(uuid.uuid4())
        query.update({TOKEN_NAME: hwm_uuid})
        new_url = ParseResult(
            url_parsed.scheme,
            url_parsed.netloc,
            url_parsed.path,
            url_parsed.params,
            urlencode(query),
            url_parsed.fragment,
        ).geturl() # Let's hope this can't introduce XSS :P
        db.addToken(hwm_uuid)
        print("ERR message=%s" % (new_url), flush=True)
con.close()
